[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = ["@sp1-contracts/=./contracts/lib/sp1-contracts/contracts/src/"]
